"""Deterministic acceptance and projection engine for Arbor stamps.

Gaia Research produces ``hh-stamp/v1`` decisions.  This module accepts those
bundles without importing Research code, retains canonical source bytes, and
projects them into ``registry/arbor/stamps.jsonl``.  Arbor is deliberately
independent of stars, ranks, and Trust Magnitude.
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from pathlib import Path
from typing import Any

import jsonschema


HEADER = "# arbor-stamp/v1 projection - generated by gaia dev arbor; do not edit\n"
FORBIDDEN_FIELDS = frozenset(
    {
        "rank",
        "ranks",
        "star",
        "stars",
        "level",
        "levels",
        "tierRank",
        "trust",
        "trustGrade",
        "trustMagnitude",
        "overallTrustGrade",
        "tm",
    }
)


class ArborError(ValueError):
    """An Arbor contract or projection invariant failed."""


def canonicalJson(value: Any) -> bytes:
    """Return canonical UTF-8 JSON with one trailing LF."""
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def arborPaths(repoRoot: str | Path) -> tuple[Path, Path, Path]:
    root = Path(repoRoot)
    arborRoot = root / "registry" / "arbor"
    return arborRoot, arborRoot / "sources", arborRoot / "stamps.jsonl"


def loadSchemas(repoRoot: str | Path) -> tuple[dict[str, Any], dict[str, Any]]:
    schemaRoot = Path(repoRoot) / "registry" / "schema"
    try:
        bundle = json.loads((schemaRoot / "hh-stamp.schema.json").read_text(encoding="utf-8"))
        projection = json.loads((schemaRoot / "arborStamp.schema.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ArborError(f"could not load Arbor schemas: {exc}") from exc
    return bundle, projection


def validateAgainst(value: Any, schema: dict[str, Any], label: str, store: dict[str, Any] | None = None) -> None:
    try:
        validator = jsonschema.Draft202012Validator(
            schema,
            registry=_schemaRegistry(store or {}),
            format_checker=jsonschema.FormatChecker(),
        )
        errors = sorted(validator.iter_errors(value), key=lambda error: list(error.absolute_path))
    except Exception as exc:
        raise ArborError(f"{label}: schema setup failed: {exc}") from exc
    if errors:
        error = errors[0]
        where = ".".join(str(part) for part in error.absolute_path) or "$"
        raise ArborError(f"{label}.{where}: {error.message}")


def _schemaRegistry(store: dict[str, Any]):
    from referencing import Registry, Resource

    registry = Registry()
    for uri, schema in store.items():
        registry = registry.with_resource(uri, Resource.from_contents(schema))
    return registry


def rejectForbiddenFields(value: Any, where: str = "bundle") -> None:
    if isinstance(value, dict):
        for key, child in value.items():
            if key in FORBIDDEN_FIELDS or key.lower() in {field.lower() for field in FORBIDDEN_FIELDS}:
                raise ArborError(f"{where}: prestige/trust field '{key}' is forbidden at the Arbor boundary")
            rejectForbiddenFields(child, f"{where}.{key}")
    elif isinstance(value, list):
        for index, child in enumerate(value):
            rejectForbiddenFields(child, f"{where}[{index}]")


def validateBundle(bundle: Any, bundleSchema: dict[str, Any]) -> dict[str, Any]:
    rejectForbiddenFields(bundle)
    validateAgainst(bundle, bundleSchema, "bundle")
    assert isinstance(bundle, dict)
    seenSkills: set[str] = set()
    for decision in bundle["decisions"]:
        skillId = decision["skillId"]
        if skillId in seenSkills:
            raise ArborError(f"bundle: duplicate skill identity '{skillId}'")
        seenSkills.add(skillId)
        stamps = decision.get("stamps", {})
        if decision["decision"] == "accepted":
            primary = decision["primaryStamp"]
            if primary not in stamps:
                raise ArborError(f"bundle: primary stamp '{primary}' is not accepted for '{skillId}'")
        if decision["denyStatus"]["status"] == "denied" and "hell-safe" in stamps:
            raise ArborError(f"bundle: denied skill '{skillId}' cannot be hell-safe")
    return bundle


def parseBundle(path: str | Path, bundleSchema: dict[str, Any]) -> tuple[dict[str, Any], bytes, str]:
    try:
        value = json.loads(Path(path).read_bytes())
    except (OSError, json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise ArborError(f"could not read acceptance bundle: {exc}") from exc
    bundle = validateBundle(value, bundleSchema)
    canonical = canonicalJson(bundle)
    return bundle, canonical, sha256(canonical)


def projectionRows(bundles: list[tuple[dict[str, Any], str]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    skillClaims: dict[str, tuple[str, str, str]] = {}
    sourceClaims: dict[str, str] = {}
    for bundle, bundleDigest in bundles:
        sourceDigest = bundle["sourceDigest"]
        priorBundle = sourceClaims.get(sourceDigest)
        if priorBundle is not None and priorBundle != bundleDigest:
            raise ArborError(f"conflicting bundles claim sourceDigest '{sourceDigest}'")
        sourceClaims[sourceDigest] = bundleDigest
        for decision in bundle["decisions"]:
            skillId = decision["skillId"]
            claim = (decision["skillMdSha256"], sourceDigest, bundleDigest)
            prior = skillClaims.get(skillId)
            if prior is not None:
                if prior != claim:
                    raise ArborError(f"conflicting identity/source claim for '{skillId}'")
                raise ArborError(f"duplicate identity/source claim for '{skillId}'")
            skillClaims[skillId] = claim
            rows.append(
                {
                    "schema": "arbor-stamp/v1",
                    "sourceDigest": sourceDigest,
                    "sourceBundleSha256": bundleDigest,
                    "acceptance": decision,
                }
            )
    rows.sort(key=lambda row: row["acceptance"]["skillId"])
    return rows


def projectionBytes(rows: list[dict[str, Any]]) -> bytes:
    return HEADER.encode("utf-8") + b"".join(canonicalJson(row) for row in rows)


def validateProjection(rows: list[dict[str, Any]], projectionSchema: dict[str, Any], bundleSchema: dict[str, Any]) -> None:
    store = {"https://gaiaskilltree.com/schema/hh-stamp/v1": bundleSchema}
    for index, row in enumerate(rows):
        rejectForbiddenFields(row, f"projection[{index}]")
        validateAgainst(row, projectionSchema, f"projection[{index}]", store)


def loadRetainedBundles(repoRoot: str | Path, bundleSchema: dict[str, Any]) -> list[tuple[dict[str, Any], str]]:
    _arborRoot, sourcesRoot, _projectionPath = arborPaths(repoRoot)
    bundles: list[tuple[dict[str, Any], str]] = []
    if not sourcesRoot.exists():
        return bundles
    for sourcePath in sorted(sourcesRoot.glob("*.json")):
        try:
            raw = sourcePath.read_bytes()
            value = json.loads(raw)
        except (OSError, json.JSONDecodeError, UnicodeDecodeError) as exc:
            raise ArborError(f"retained bundle '{sourcePath.name}' is unreadable: {exc}") from exc
        bundle = validateBundle(value, bundleSchema)
        canonical = canonicalJson(bundle)
        digest = sha256(canonical)
        if sourcePath.name != f"{digest}.json":
            raise ArborError(f"retained bundle '{sourcePath.name}' is not digest-addressed")
        if raw != canonical:
            raise ArborError(f"retained bundle '{sourcePath.name}' is not canonical JSON")
        bundles.append((bundle, digest))
    return bundles


def expectedState(repoRoot: str | Path) -> tuple[list[tuple[dict[str, Any], str]], list[dict[str, Any]], bytes]:
    bundleSchema, projectionSchema = loadSchemas(repoRoot)
    bundles = loadRetainedBundles(repoRoot, bundleSchema)
    rows = projectionRows(bundles)
    validateProjection(rows, projectionSchema, bundleSchema)
    return bundles, rows, projectionBytes(rows)


def checkProjection(repoRoot: str | Path) -> None:
    _bundles, _rows, expected = expectedState(repoRoot)
    _arborRoot, _sourcesRoot, projectionPath = arborPaths(repoRoot)
    try:
        actual = projectionPath.read_bytes()
    except OSError as exc:
        raise ArborError(f"could not read Arbor projection: {exc}") from exc
    if actual != expected:
        raise ArborError("Arbor projection drift detected; run 'gaia dev arbor replay'")


def atomicWrite(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, tempName = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(tempName, path)
    except BaseException:
        try:
            os.unlink(tempName)
        except FileNotFoundError:
            pass
        raise


def replayProjection(repoRoot: str | Path) -> int:
    bundles, rows, expected = expectedState(repoRoot)
    _arborRoot, _sourcesRoot, projectionPath = arborPaths(repoRoot)
    atomicWrite(projectionPath, expected)
    return len(rows)


def importBundle(repoRoot: str | Path, bundlePath: str | Path) -> tuple[str, int, bool]:
    bundleSchema, projectionSchema = loadSchemas(repoRoot)
    existing = loadRetainedBundles(repoRoot, bundleSchema)
    existingRows = projectionRows(existing)
    validateProjection(existingRows, projectionSchema, bundleSchema)
    _arborRoot, sourcesRoot, projectionPath = arborPaths(repoRoot)
    currentProjection = projectionPath.read_bytes()
    expectedCurrent = projectionBytes(existingRows)
    if currentProjection != expectedCurrent:
        raise ArborError("Arbor projection drift detected; import refused")

    bundle, canonical, bundleDigest = parseBundle(bundlePath, bundleSchema)
    alreadyPresent = any(digest == bundleDigest for _value, digest in existing)
    future = existing if alreadyPresent else [*existing, (bundle, bundleDigest)]
    futureRows = projectionRows(future)
    validateProjection(futureRows, projectionSchema, bundleSchema)
    futureProjection = projectionBytes(futureRows)
    if alreadyPresent:
        return bundleDigest, len(futureRows), False

    sourcePath = sourcesRoot / f"{bundleDigest}.json"
    projectionBackup = currentProjection
    try:
        atomicWrite(sourcePath, canonical)
        atomicWrite(projectionPath, futureProjection)
    except BaseException:
        try:
            sourcePath.unlink(missing_ok=True)
            atomicWrite(projectionPath, projectionBackup)
        except BaseException as rollbackError:
            raise ArborError(f"Arbor import failed and rollback failed: {rollbackError}") from rollbackError
        raise
    return bundleDigest, len(futureRows), True
